I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
I, John Adams, am sorry for sleeping in class.
